### ISSUE TITLE
cg_iRIC_Read_Grid2d_Str_Size fails when fastmech contains 3d results

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/iriclib_v4#25]
cg_iRIC_Read_Grid2d_Str_Size fails when the cgns file contains both 2d and 3d grids

Two unit tests were added to unittests_cgnsfile to demonstrate:

void case_GridRead_FaSTMECH();                            
void case_GridRead_FaSTMECH_3d_results();     // FAILS in iriclib_v4

The equivalent cases were also added to i-RIC/iriclib to be merged by pull request i-RIC/iriclib#92

Here's the original i-RIC v3 project:
[fm-ex3.zip](https://github.com/i-RIC/iriclib_v4/files/7715698/fm-ex3.zip)

**Comment by kskinoue0612** [comment]
Hi Scott,

I'm sorry, I should have noticed earlier, I think I know how to fix this.
Please use cg_iRIC_Read_Grid2d_Str_Size_WithGridId, instead of cg_iRIC_Read_Grid2d_Str_Size().

I mean, use 

```
call cg_iRIC_Read_Grid2d_Str_Size_WithGridId(fid, 1, isize, jsize)
```

instead of

```
call cg_iRIC_Read_Grid2d_Str_Size(fid, isize, jsize)
```

because, when there is the 3d results, call cg_iRIC_Read_Grid2d_Str_Size try to get information from last grid, that is 3d grid.

**Comment by scharlton2** [comment]
Hi Keisuke,

That did work.  But it seems to be redundant.  If the grid_id is always 1 for the 2d grid then isn't the grid_id unnecessary? 

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the contact, and glad to hear that it worked.

I understand that you feel it redundant.
Actually, the grid with gridid 1 is 2d grid, and grid with gridid 2 is 3d
grid in FASTMECH’s case, so I think cg_iRIC_Grid2d_Str_Size should refer to
grid with gridid 1.

I think I can fix it. I’ll work on it, and contact you when I’ve got
progress.

Thank you,

Keisuke

2022年5月18日(水) 6:33 Charlton, Scott R. ***@***.***>:
